# Configuration of Hugo
title: "航空先进动力性能与稳定性课题组"
baseURL: "https://example.com/"

defaultContentLanguage: zh
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

cascade:
  - target:
      path: /slides/**
      kind: page

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [ ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$" ]
disableAliases: true
outputs:
  home: [ HTML, RSS, headers, redirects, backlinks ]
  section: [ HTML, RSS ]
imaging:
  resampleFilter: Lanczos
  quality: 90
  anchor: Smart
  hint: picture
timeout: "600s"
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
