# Languages
zh:
  languageCode: zh-cn
  languageName: 中文
  weight: 1
  title: 航空先进动力性能与稳定性课题组
  params:
    description: 航空先进动力性能与稳定性课题组主页

en:
  languageCode: en-us
  languageName: English
  weight: 2
  title: 航空先进动力性能与稳定性课题组
  params:
    description: Aero-Engine Performance and Stability Group homepage
