main:
  - name: 主页
    url: /#home
    weight: 10
  - name: 最新研究
    url: /#latest-research
    weight: 20
  - name: 团队成员
    url: /#members
    weight: 30
  - name: 成果发表
    url: /#achievements
    weight: 40
  - name: 活动相册
    url: /#gallery
    weight: 50
  - name: 招募信息
    url: /#activity
    weight: 60
  - name: 联系方式
    url: /#contact
    weight: 70
