main:
  - name: Home
    url: /en/#home
    weight: 10
  - name: Latest Research
    url: /en/#latest-research
    weight: 20
  - name: Team Members
    url: /en/#members
    weight: 30
  - name: Publications
    url: /en/#achievements
    weight: 40
  - name: Gallery
    url: /en/#gallery
    weight: 50
  - name: Open Positions
    url: /en/#activity
    weight: 60
  - name: Contact
    url: /en/#contact
    weight: 70
